<?php
declare(strict_types=1);

use Loki\Components\Component\ComponentViewModelInterface;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\View\Element\Template;

/** @version 2.0.26 */
/** @var Template $block */
/** @var CssClass $css */
/** @var ComponentViewModelInterface $viewModel */
?>
<div class="<?= /* @noEscape */
$css('grid grid-2-cols gap-4') ?>">
    <div class="<?= /* @noEscape */
    $css('field email required', 'field-container') ?>">
        <label class="<?= /* @noEscape */
        $css('label', 'label') ?>" for="<?= /* @noEscape */ $viewModel->getElementId() ?>-email">
            <span><?= /* @noEscape */
                __('Email') ?></span>
        </label>
        <div class="<?= /* @noEscape */
        $css('control', 'field-control') ?>">
            <input
                name="login[email]"
                class="<?= /* @noEscape */
                $css('form-input w-full', 'field-input') ?>"
                required
                :value="email"
                @change="setEmail"
                autocomplete="off"
                id="<?= /* @noEscape */ $viewModel->getElementId() ?>-email"
                type="email"
                title="<?= /* @noEscape */
                __('Email') ?>">
        </div>
    </div>

    <div class="<?= /* @noEscape */
    $css('field password required', 'field-container') ?>">
        <label class="<?= /* @noEscape */
        $css('label', 'label') ?>" for="<?= /* @noEscape */ $viewModel->getElementId() ?>-password">
            <span><?= /* @noEscape */
                __('Password') ?></span>
        </label>
        <div class="<?= /* @noEscape */
        $css('control flex items-center', 'field-control') ?>">
            <input
                name="login[password]"
                class="<?= /* @noEscape */
                $css('form-input w-full', 'field-input') ?>"
                required
                :value="password"
                @change="setPassword"
                autocomplete="off"
                id="<?= /* @noEscape */ $viewModel->getElementId() ?>-password"
                :type="passwordFieldType"
                title="<?= /* @noEscape */
                __('Password') ?>">

            <button
                type="button"
                @click="toggleVisible"
                :aria-label="buttonAriaLabel"
                class="<?= /* @noEscape */ $css('px-4 py-3', 'button') ?>">
                <template x-if="passwordVisible">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5"
                         width="20" height="20" aria-hidden="true">
                        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
                        <path fill-rule="evenodd"
                              d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
                              clip-rule="evenodd"></path>
                    </svg>
                </template>

                <template x-if="passwordNotVisible">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5"
                         width="20" height="20" aria-hidden="true">
                        <path fill-rule="evenodd"
                              d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z"
                              clip-rule="evenodd"></path>
                        <path
                            d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z"></path>
                    </svg>
                </template>
            </button>
        </div>
    </div>

    <div class="<?= /* @noEscape */
$css('actions-toolbar pt-6 pb-2', 'toolbar') ?>">
        <button
            type="button"
            class="<?= /* @noEscape */ $css('btn btn-primary disabled:opacity-75', 'toolbar-button') ?>"
            @click="submit">
            <span>><?= __('Sign In') ?></span>
        </button>

        <a
            class="<?= /* @noEscape */ $css('underline text-secondary', 'forgot-password-link') ?>"
            href="<?= __($block->getUrl('customer/account/forgotpassword')) ?>">
            <span><?= __('Forgot Your Password?') ?></span>
        </a>
    </div>
</div>
