<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ExampleLokiCheckoutStepLoginComponent', () => ({
            ...LokiComponentType,
            email: '',
            password: '',
            passwordFieldType: 'password',
            setEmail() {
                this.email = this.$el.value;
            },
            setPassword() {
                this.password = this.$el.value;
            },
            isButtonDisabled() {
                return !this.email || !this.password;
            },
            submit() {
                this.post({
                    email: this.email,
                    password: this.password,
                });

                Alpine.store('LokiLocalStorage').refresh('customer');
            },
            buttonAriaLabel() {
                if (this.passwordFieldType === 'text') {
                    return '<?= /* @noEscape */ __('Hide password') ?>';
                }

                return '<?= /* @noEscape */ __('Show password') ?>';
            },
            passwordVisible() {
                return this.passwordFieldType === 'text';
            },
            passwordNotVisible() {
                return this.passwordFieldType === 'password';
            },
            togglePasswordFieldType() {
                this.passwordFieldType = this.passwordFieldType === 'password' ? 'text' : 'password';
            }
        }));
    });
</script>
